apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: my-app
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://myapp.local/api/v1"
  DATABASE_URL: "postgres://postgres:postgres@database:5432/mydb"
