apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: my-app
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=  # 'postgres'를 base64로 인코딩
  DB_USER: cG9zdGdyZXM=      # 실제 운영환경에서는 더 강력한 값 사용 필요 
